FROM python:3.12-bookworm

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    supervisor \
    gcc \
    curl \
    socat && \
    rm -rf /var/lib/apt/lists/* && \
    curl -Ls https://github.com/radareorg/radare2/releases/download/5.9.0/radare2-5.9.0.tar.xz | tar xJv && \
    radare2-5.9.0/sys/install.sh


RUN groupadd -r app && useradd -r -g app app

COPY chapter_2 .
COPY logic.py .
COPY generation_utils.py .
COPY db.py .

RUN mkdir -p /run/supervisord && \
    chown -R app:app /run/supervisord && \
    chown -R app:app .

RUN pip3 install --no-cache-dir -r requirements.txt

USER app

EXPOSE 9990-9992

CMD ["supervisord", "-c", "supervisord.conf"]

